"""extra models

Revision ID: 66ec614371c9
Revises: 96ce9b408a6f
Create Date: 2019-04-30 14:46:47.641000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ec614371c9'
down_revision = '96ce9b408a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fati',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valve',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fati_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fati_id'], ['fati.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valve_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('valve_id', sa.Integer(), nullable=True),
    sa.Column('on_bit', sa.BINARY(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['valve_id'], ['valve.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('valve_configuration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valve_configuration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('valve_config')
    op.drop_table('valve')
    op.drop_table('system_configuration')
    op.drop_table('fati')
    # ### end Alembic commands ###
