"""update number of valves

Revision ID: 377688a36ceb
Revises: 
Create Date: 2021-06-30 20:38:36.131928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377688a36ceb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valve_configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=144), nullable=False),
    sa.Column('configtype', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valve_configuration')
    # ### end Alembic commands ###
